# This is a config for E2B sandbox template.
# You can use template ID (zzxs8jf03nbx43dpnkd9) or template name (vibe-studio) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("vibe-studio") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-studio") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-studio')

team_id = "c347fab0-30d9-4f18-9fb1-a08e8dc0d29b"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-studio"
template_id = "zzxs8jf03nbx43dpnkd9"
